spring.application.name=namasvi-cab

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://ep-patient-frog-aqidlke7-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=PJ
spring.datasource.password=npg_yH98lroOhwfa
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D635166546A576E5A7234753778214125442A47
app.jwt.expiration=86400000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
